/**
 * Production-Grade Excel & CSV Exporter for Primary Slitter Production Plans
 * Replicates the authoritative GPAK Document GPAK/QR/PL/01 Layout
 * Strict Implementation of SRS Sections 40, 41, 77
 */

import * as XLSX from 'xlsx';
import { SlitterPlan, PlanningRun, VA05Order, PlanItem } from '../types';

/**
 * Generates an Excel workbook for a single Slitter Plan matching GPAK/QR/PL/01
 */
export function exportSinglePlanToExcel(plan: SlitterPlan): Uint8Array {
  const wb = XLSX.utils.book_new();
  const ws = createPlanWorksheet(plan);
  XLSX.utils.book_append_sheet(wb, ws, plan.plan_number.slice(0, 31));
  return XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
}

/**
 * Generates a complete Multi-Plan Planning Run Excel Workbook
 * Contains Summary Sheet + Individual Plan Sheets + Remaining Demand Sheet
 */
export function exportCompleteRunToExcel(
  run: PlanningRun,
  plans: SlitterPlan[],
  remainingOrders: VA05Order[]
): Uint8Array {
  const wb = XLSX.utils.book_new();

  // 1. Run Summary Sheet
  const summaryData = [
    ['PRIMARY SLITTER PLANNING RUN SUMMARY'],
    ['Run Number:', run.run_number, 'Film Grade:', run.film],
    ['Target Quantity (kg):', run.target_quantity_kg, 'Planned Quantity (kg):', run.planned_quantity_kg],
    ['Target Range (±5%):', run.target_min_kg ? `${run.target_min_kg} - ${run.target_max_kg} kg` : 'N/A', 'Target Deviation:', `${run.target_deviation_percent !== undefined ? run.target_deviation_percent : 0}%`],
    ['Remaining Quantity (kg):', run.remaining_quantity_kg, 'Plans Generated:', plans.length],
    ['Orders Completely Closed:', run.orders_closed_count, 'Orders Partially Fulfilled:', run.orders_partial_count],
    ['Trim Mode:', run.trim_rule_mode || 'NORMAL', 'Trim Limits:', `${run.min_trim_mm_used || 160} - ${run.max_trim_mm_used || 220} mm`],
    ['Status:', run.status, 'Generated By:', run.created_by],
    ['Created At:', run.created_at, 'Stop Reason:', run.stop_reason || 'N/A'],
    [],
    ['PLAN SUMMARY TABLE'],
    ['Plan No.', 'Film', 'UPS', 'Deckle (mm)', 'Slit Width (mm)', 'Trim (mm)', 'Length (m)', 'Reps', 'MR Length (m)', 'Planned Qty (kg)', 'Status'],
  ];

  plans.forEach(p => {
    summaryData.push([
      p.plan_number,
      p.film,
      p.ups,
      p.deckle_mm,
      p.total_slit_width_mm,
      p.trim_mm,
      p.length_m,
      p.repetitions,
      p.planned_mr_length_m,
      p.planned_quantity_kg,
      p.status,
    ]);
  });

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // 2. Individual Plan Sheets (One for each generated plan)
  plans.forEach((plan, idx) => {
    const sheetName = `Plan_${String(idx + 1).padStart(2, '0')}`;
    const wsPlan = createPlanWorksheet(plan);
    XLSX.utils.book_append_sheet(wb, wsPlan, sheetName);
  });

  // 3. Remaining Orders Sheet
  const remainingData: any[][] = [
    ['REMAINING DEMAND BACKLOG AFTER PLANNING RUN'],
    ['Film:', run.film, 'Run ID:', run.run_number],
    [],
    ['SO#', 'Item#', 'Customer', 'Width (mm)', 'Length (m)', 'Core', 'TS', 'Original Qty (kg)', 'Produced (kg)', 'Remaining Qty (kg)', 'Status', 'Delivery Date'],
  ];

  remainingOrders.forEach(o => {
    remainingData.push([
      o.sales_order,
      o.item_number,
      o.customer,
      o.width_mm,
      o.length_m,
      o.core,
      o.treatment_side,
      o.balance_qty,
      o.produced_qty,
      o.remaining_qty,
      o.status,
      o.delivery_date || '',
    ]);
  });

  const wsRemaining = XLSX.utils.aoa_to_sheet(remainingData);
  XLSX.utils.book_append_sheet(wb, wsRemaining, 'Remaining Demand');

  return XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
}

export interface ConsolidatedPlanItemRow {
  key: string;
  id: string;
  position_label: string;
  station: 'SIDE_A' | 'SIDE_B' | 'MIXED';
  station_label: string;
  sales_order: string;
  item_number: number | string;
  customer: string;
  film: string;
  length_m: number;
  core: number | string;
  treatment_side: string;
  width_mm: number;
  total_weight_kg: number;
  size_mm: number;
  ups: number;
  deckle_mm: number;
  reels: number;
  weight_per_pack_kg: number;
  is_closed: boolean;
  is_future_replacement?: boolean;
  raw_items: PlanItem[];
}

export function formatNumberRangeList(nums: number[]): string {
  if (!nums || nums.length === 0) return '';
  const sorted = Array.from(new Set(nums.filter(n => typeof n === 'number' && !isNaN(n)))).sort((a, b) => a - b);
  if (sorted.length === 0) return '';
  if (sorted.length === 1) return `${sorted[0]}`;

  const ranges: string[] = [];
  let start = sorted[0];
  let end = sorted[0];

  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] === end + 1) {
      end = sorted[i];
    } else {
      ranges.push(start === end ? `${start}` : `${start}–${end}`);
      start = sorted[i];
      end = sorted[i];
    }
  }
  ranges.push(start === end ? `${start}` : `${start}–${end}`);
  return ranges.join(', ');
}

/**
 * Consolidates plan items sharing the same Sales Order, Item Number, Customer, Size, Core, Treatment & Length.
 * Combines individual UPS cuts into a single unified execution row with total UPS count, total deckle, and total weight.
 */
export function consolidatePlanItems(items: PlanItem[] = []): ConsolidatedPlanItemRow[] {
  if (!items || items.length === 0) return [];

  const map = new Map<string, PlanItem[]>();

  items.forEach(item => {
    const isFuture = !!item.is_future_replacement;
    const soClean = (item.sales_order || '').trim();
    const itemNumClean = `${item.item_number || ''}`.trim();
    const custClean = (item.customer || '').trim();
    const w = Number(item.width_mm || 0);
    const l = Number(item.length_m || 0);
    const c = `${item.core || ''}`.trim();
    const ts = (item.treatment_side || '').trim();

    const key = `${soClean}__${custClean}__${w}__${l}__${c}__${ts}__${isFuture ? '1' : '0'}`;
    if (!map.has(key)) {
      map.set(key, []);
    }
    map.get(key)!.push(item);
  });

  const consolidated: ConsolidatedPlanItemRow[] = [];

  map.forEach((groupedItems, key) => {
    const first = groupedItems[0];
    const isFuture = !!first.is_future_replacement;

    // Total UPS sum
    const totalUps = groupedItems.reduce((sum, it) => {
      const up = it.is_future_replacement ? 0 : (it.initial_ups !== undefined ? it.initial_ups : (it.ups || 1));
      return sum + up;
    }, 0);

    // Sum Total Weight
    const totalWeightKg = Number(groupedItems.reduce((sum, it) => sum + (it.total_weight_kg || 0), 0).toFixed(2));

    // Sum Reels
    const totalReels = groupedItems.reduce((sum, it) => sum + (it.reels || 0), 0);

    // Sum Weight per pack
    const totalWeightPerPack = Number(groupedItems.reduce((sum, it) => sum + (it.weight_per_pack_kg || 0), 0).toFixed(2));

    // Deckle (mm)
    const deckleMm = isFuture ? 0 : (first.width_mm * totalUps);

    // Collect all Positions and Arm numbers
    const allPositions: number[] = [];
    const allArms: number[] = [];

    groupedItems.forEach((it, idx) => {
      let foundPosInLabel = false;
      let foundArmInLabel = false;

      if (it.position_label) {
        const posMatch = it.position_label.match(/Pos\s*([0-9,\s–-]+)/i);
        const armMatch = it.position_label.match(/Arm\s*([0-9,\s–-]+)/i);

        if (posMatch) {
          foundPosInLabel = true;
          const matchedStr = posMatch[1];
          const chunks = matchedStr.split(/[,]/);
          chunks.forEach(ch => {
            const range = ch.trim().split(/[–-]/);
            if (range.length === 2) {
              const rStart = parseInt(range[0].trim(), 10);
              const rEnd = parseInt(range[1].trim(), 10);
              if (!isNaN(rStart) && !isNaN(rEnd)) {
                for (let n = rStart; n <= rEnd; n++) allPositions.push(n);
              }
            } else if (range.length === 1) {
              const single = parseInt(range[0].trim(), 10);
              if (!isNaN(single)) allPositions.push(single);
            }
          });
        }

        if (armMatch) {
          foundArmInLabel = true;
          const matchedStr = armMatch[1];
          const chunks = matchedStr.split(/[,]/);
          chunks.forEach(ch => {
            const range = ch.trim().split(/[–-]/);
            if (range.length === 2) {
              const rStart = parseInt(range[0].trim(), 10);
              const rEnd = parseInt(range[1].trim(), 10);
              if (!isNaN(rStart) && !isNaN(rEnd)) {
                for (let n = rStart; n <= rEnd; n++) allArms.push(n);
              }
            } else if (range.length === 1) {
              const single = parseInt(range[0].trim(), 10);
              if (!isNaN(single)) allArms.push(single);
            }
          });
        }
      }

      if (!foundPosInLabel) {
        if (it.positions && it.positions.length > 0) {
          it.positions.forEach(p => allPositions.push(p));
        } else if (it.position !== undefined) {
          allPositions.push(it.position);
        }
      }

      if (!foundArmInLabel && it.position !== undefined) {
        allArms.push(it.position);
      }
    });

    const posRangeStr = formatNumberRangeList(allPositions);
    const armRangeStr = formatNumberRangeList(allArms);

    let posLabel = first.position_label || `${first.position || 1}`;
    if (posRangeStr && armRangeStr && posRangeStr !== armRangeStr) {
      posLabel = `Pos ${posRangeStr} (Arms ${armRangeStr})`;
    } else if (posRangeStr) {
      posLabel = `Pos ${posRangeStr}`;
    } else if (armRangeStr) {
      posLabel = `Arm ${armRangeStr}`;
    }

    // Stations
    const countA = groupedItems.filter(it => (it.station || (it.position <= 8 ? 'SIDE_A' : 'SIDE_B')) === 'SIDE_A').length;
    const countB = groupedItems.filter(it => (it.station || (it.position <= 8 ? 'SIDE_A' : 'SIDE_B')) === 'SIDE_B').length;

    let station: 'SIDE_A' | 'SIDE_B' | 'MIXED' = 'SIDE_A';
    let stationLabel = 'SIDE A';

    if (countA > 0 && countB === 0) {
      station = 'SIDE_A';
      stationLabel = 'SIDE A';
    } else if (countB > 0 && countA === 0) {
      station = 'SIDE_B';
      stationLabel = 'SIDE B';
    } else if (countA > 0 && countB > 0) {
      station = 'MIXED';
      stationLabel = `A: ${countA} | B: ${countB}`;
    }

    consolidated.push({
      key,
      id: first.id,
      position_label: posLabel,
      station,
      station_label: stationLabel,
      sales_order: first.sales_order,
      item_number: first.item_number,
      customer: first.customer,
      film: first.film,
      length_m: first.length_m,
      core: first.core,
      treatment_side: first.treatment_side,
      width_mm: first.width_mm,
      total_weight_kg: totalWeightKg,
      size_mm: first.width_mm,
      ups: totalUps,
      deckle_mm: deckleMm,
      reels: totalReels,
      weight_per_pack_kg: totalWeightPerPack,
      is_closed: groupedItems.every(it => it.is_closed),
      is_future_replacement: isFuture,
      raw_items: groupedItems,
    });
  });

  return consolidated;
}

/**
 * Creates a worksheet with the exact GPAK/QR/PL/01 Primary Slitter Layout
 */
function createPlanWorksheet(plan: SlitterPlan): XLSX.WorkSheet {
  const rows: any[][] = [];

  const consolidatedItems = consolidatePlanItems(plan.items || []);
  const initialActiveUps = consolidatedItems.reduce((sum, it) => sum + (it.is_future_replacement ? 0 : it.ups), 0);
  const initialActiveSlitWidth = consolidatedItems.reduce((sum, it) => sum + (it.is_future_replacement ? 0 : it.deckle_mm), 0);

  // Top Title Bar
  rows.push(['PLAN NO:', plan.plan_number, '', '', `${plan.machine_name || 'PRIMARY SLITTER'} - CUTTING SCHEDULE`, '', '', '', 'DOC REF:', plan.doc_ref]);
  rows.push(['FILM:', plan.film, '', '', 'LENGTH (m):', plan.length_m, '', '', 'REV NO:', plan.rev_no]);
  rows.push(['THICKNESS (µm):', plan.thickness_micron, '', '', 'DENSITY (g/cm³):', plan.density, '', '', 'ISSUE DATE:', plan.issue_date]);
  rows.push(['TOTAL DECKLE (mm):', plan.deckle_mm, 'UTILIZED (mm):', plan.total_slit_width_mm, 'TRIM (mm):', plan.trim_mm, 'ALLOWED TRIM (mm):', plan.allowed_trim_mm, 'WASTE (%):', `${plan.waste_percent}%`]);
  rows.push(['PLANNED MR LENGTH (m):', plan.planned_mr_length_m, 'REPETITIONS:', plan.repetitions, 'MILL ROLL WT (kg):', plan.mill_roll_weight_kg, 'TRIM WT (kg):', plan.trim_weight_kg, 'ACTIVE INITIAL UPS:', `${initialActiveUps} / 16`]);
  rows.push([]);

  // Table Headers
  rows.push([
    'SO#',
    'Item#',
    'CUSTOMER',
    'Length (m)',
    'Core',
    'TS',
    'Width (mm)',
    'REELS',
    'WEIGHT (kg)',
    'SIZE (mm)',
    'UPS',
    'DECKLE (mm)',
    'REELS PRODUCED',
    'WT/PACK (kg)',
    'TOT.WT (kg)',
  ]);

  // Data Rows (Consolidated unique order lines)
  consolidatedItems.forEach(item => {
    const isFuture = item.is_future_replacement;
    const displayUps = item.ups;
    const displayDeckle = item.deckle_mm;
    const displayWtPack = item.weight_per_pack_kg;

    rows.push([
      item.sales_order,
      item.item_number,
      isFuture ? `${item.customer} [FUTURE SHIFT]` : item.customer,
      item.length_m,
      `${item.core}"`,
      item.treatment_side,
      item.width_mm,
      item.reels,
      item.total_weight_kg,
      item.width_mm,
      displayUps,
      displayDeckle,
      item.reels,
      displayWtPack,
      item.total_weight_kg,
    ]);
  });

  // Empty rows if needed
  for (let pos = consolidatedItems.length + 1; pos <= 8; pos++) {
    rows.push(['-', '-', '-', '-', '-', '-', '-', 0, 0, '-', 0, 0, 0, 0, 0]);
  }

  // Totals Row
  rows.push([
    'TOTAL',
    '',
    '',
    '',
    '',
    '',
    '',
    plan.total_reels,
    plan.order_weight_kg,
    'INITIAL TOTALS',
    initialActiveUps,
    initialActiveSlitWidth,
    plan.total_reels,
    plan.weight_per_pack_total_kg,
    plan.planned_quantity_kg,
  ]);

  rows.push([]);

  // Dynamic Size Changes / Operator Instructions
  if (plan.changes && plan.changes.length > 0) {
    rows.push(['OPERATOR CHANGE INSTRUCTIONS (DYNAMIC SIZE REPLACEMENT):']);
    plan.changes.forEach(ch => {
      rows.push(['>>>', ch.instruction, `(Position ${ch.position}: ${ch.old_order_ref} → ${ch.new_order_ref})`]);
    });
  } else {
    rows.push(['OPERATOR INSTRUCTIONS:', 'Standard slitting pattern across all repetitions. No in-run size replacement.']);
  }

  rows.push([]);
  rows.push(['PRODUCTION FLOOR LOGS (To be filled by Slitter Operator):']);
  rows.push(['Starting Time:', '', 'Completion Time:', '', 'Duration (hrs):', '']);
  rows.push(['Repetitions Completed:', '', 'Rejections (kg):', '', 'Consumed Length (m):', '']);
  rows.push(['Operator Signature:', '', 'Quality Inspector:', '', 'Date:', '']);

  const ws = XLSX.utils.aoa_to_sheet(rows);

  // Set column widths
  ws['!cols'] = [
    { wch: 8 },  // Pos
    { wch: 12 }, // SO#
    { wch: 8 },  // Item#
    { wch: 36 }, // Customer
    { wch: 12 }, // Length
    { wch: 6 },  // Core
    { wch: 6 },  // TS
    { wch: 12 }, // Width
    { wch: 8 },  // Reels
    { wch: 14 }, // Weight
    { wch: 10 }, // Size
    { wch: 6 },  // Ups
    { wch: 12 }, // Deckle
    { wch: 14 }, // Reels Produced
    { wch: 14 }, // Wt/pack
    { wch: 14 }, // Tot.wt
  ];

  return ws;
}

/**
 * Triggers file download in browser
 */
export function downloadExcelBuffer(buffer: Uint8Array, filename: string) {
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
