import { FilmMaster, PlanningRules } from '../types';

export const MIN_SLIT_WIDTH_MM = 355;

export const DEFAULT_PLANNING_RULES: PlanningRules = {
  id: 'rule-v1.0',
  version: '1.0',
  deckle_width_mm: 10400,
  min_trim_mm: 160,
  max_trim_mm: 220,
  min_slit_width_mm: 355,
  min_ups: 3,
  max_ups: 16,
  full_repetition_length_m: 19500,
  half_repetition_length_m: 9750,
  weight_divisor: 1000000,
  target_tolerance_percent: 3,
  updated_at: '2026-08-19T00:00:00Z',
};

export const FILM_MASTERS: FilmMaster[] = [
  {
    code: 'TNO20',
    name: 'Transparent Non Heat Sealable BOPP Film 20µ',
    category: 'TRANSPARENT',
    thickness_micron: 20,
    density: 0.91,
    standard_length_m: 19500,
    rejection_code: 'R-TNO20',
  },
  {
    code: 'TNO18',
    name: 'Transparent Non Heat Sealable BOPP Film 18µ',
    category: 'TRANSPARENT',
    thickness_micron: 18,
    density: 0.91,
    standard_length_m: 19500,
    rejection_code: 'R-TNO18',
  },
  {
    code: 'TNO15',
    name: 'Transparent Non Heat Sealable BOPP Film 15µ',
    category: 'TRANSPARENT',
    thickness_micron: 15,
    density: 0.91,
    standard_length_m: 19500,
    rejection_code: 'R-TNO15',
  },
  {
    code: 'TH21-20',
    name: 'Transparent Heat Sealable BOPP Film 20µ',
    category: 'TRANSPARENT',
    thickness_micron: 20,
    density: 0.91,
    standard_length_m: 19500,
    rejection_code: 'R-TH21-20',
  },
  {
    code: 'TH21-25',
    name: 'Transparent Heat Sealable BOPP Film 25µ',
    category: 'TRANSPARENT',
    thickness_micron: 25,
    density: 0.91,
    standard_length_m: 15500,
    rejection_code: 'R-TH21-25',
  },
  {
    code: 'TH21-30',
    name: 'Transparent Heat Sealable BOPP Film 30µ',
    category: 'TRANSPARENT',
    thickness_micron: 30,
    density: 0.91,
    standard_length_m: 12900,
    rejection_code: 'R-TH21-30',
  },
  {
    code: 'TH21-15',
    name: 'Transparent Heat Sealable BOPP Film 15µ',
    category: 'TRANSPARENT',
    thickness_micron: 15,
    density: 0.91,
    standard_length_m: 26000,
    rejection_code: 'R-TH21-15',
  },
  {
    code: 'MZ18',
    name: 'Metallized Heat Sealable BOPP Film 18µ',
    category: 'METALLIZED',
    thickness_micron: 18,
    density: 0.91,
    standard_length_m: 24000,
    rejection_code: 'R-MZ18',
  },
  {
    code: 'MZ20',
    name: 'Metallized Heat Sealable BOPP Film 20µ',
    category: 'METALLIZED',
    thickness_micron: 20,
    density: 0.91,
    standard_length_m: 20000,
    rejection_code: 'R-MZ20',
  },
  {
    code: 'MZ10S-20',
    name: 'Metallized Improved Barrier & SIT Film 20µ',
    category: 'METALLIZED',
    thickness_micron: 20,
    density: 0.91,
    standard_length_m: 18700,
    rejection_code: 'R-MZ10S-20',
  },
  {
    code: 'MZ10MB-15',
    name: 'Metallized Improved Barrier & SIT Film 15µ',
    category: 'METALLIZED',
    thickness_micron: 15,
    density: 0.91,
    standard_length_m: 26700,
    rejection_code: 'R-MZ10MB-15',
  },
  {
    code: 'MATTWL15',
    name: 'Matt Bothsides Heat Sealable BOPP Film 15µ',
    category: 'MATT',
    thickness_micron: 15,
    density: 0.91,
    standard_length_m: 13350,
    rejection_code: 'R-MATTWL15',
  },
  {
    code: 'THOW25',
    name: 'Transparent O/W Heat Sealable BOPP Film 25µ',
    category: 'TRANSPARENT',
    thickness_micron: 25,
    density: 0.91,
    standard_length_m: 4000,
    rejection_code: 'R-THOW25',
  },
  {
    code: 'TNIT-23',
    name: 'Transparent Tape Grade BOPP Film 23µ',
    category: 'TRANSPARENT',
    thickness_micron: 23,
    density: 0.91,
    standard_length_m: 16900,
    rejection_code: 'R-TNIT-23',
  },
  {
    code: 'THO20',
    name: 'Transparent Non Heat Sealable BOPP Film 20µ',
    category: 'TRANSPARENT',
    thickness_micron: 20,
    density: 0.91,
    standard_length_m: 10000,
    rejection_code: 'R-THO20',
  },
];
