/**
 * GPAK MSL <-> PS01 Feasibility Handshake Adapter
 * 
 * CRITICAL ARCHITECTURAL CONSTRAINTS:
 * - PS01 Primary Slitter optimizer is 100% FROZEN.
 * - This adapter acts as a non-invasive bridge to evaluate whether candidate
 *   Jumbo Roll requirements generated by MSL are physically and mathematically
 *   manufacturable on PS01 (10,400 mm mother deckle, 140-250 mm normal trim, duplex balance).
 * - Implements strict Priority Ordering for Trim Relaxation (Last Resort Only):
 *   Priority A: Normal MSL trim (20-30mm) + Normal PS01 rules (140-250mm) -> GREEN
 *   Priority B: Explore all viable combination permutations
 *   Priority C: MSL Trim adjustment within [20, 30] mm -> YELLOW (MSL_TRIM_ADJUSTED)
 *   Priority D/E: Upstream PS01 Trim relaxation -> YELLOW (PS01_TRIM_RELAXED)
 *   Otherwise: RED (Infeasible)
 */

import { DEFAULT_PLANNING_RULES } from '../masterData';
import { VA05Order, SlitterPlan, PlanItem, PlanSegment } from '../../types';
import { generatePrimarySlitterPlans, OptimizationResult } from '../optimizer/deckleOptimizer';
import { JumboRequirement } from '../../types/metallizer';

export type PS01HandshakeStatus = 'GREEN' | 'YELLOW' | 'RED';
export type TrimRelaxationType = 'NONE' | 'MSL_TRIM_ADJUSTED' | 'PS01_TRIM_RELAXED';

export interface PS01FeasibilityEvaluation {
  status: PS01HandshakeStatus;
  is_feasible: boolean;
  ps01_deckle_mm: number;
  jumbo_width_mm: number;
  ps01_ups: number;
  ps01_cut_combination: number[];
  ps01_total_width_mm: number;
  ps01_trim_mm: number;
  ps01_deckle_efficiency_percent: number;
  ps01_duplex_balanced: boolean;
  side_a_ups: number;
  side_b_ups: number;
  relaxation_type: TrimRelaxationType;
  relaxation_flag?: string;
  explanation: string;
}

export interface CandidateJumboProposal {
  film: string;
  thickness_micron: number;
  finished_widths: number[];
  msl_ups: number;
  target_msl_trim_mm: number;
  jumbo_width_mm: number;
  package_length_m: number;
  package_multiple: number;
  jumbo_length_m: number;
  diameter_mm: number;
  matching_orders: VA05Order[];
}

// Memoization caches for high-speed deterministic feasibility queries
const comboFeasibilityCache = new Map<string, PS01FeasibilityEvaluation>();
const singleFeasibilityCache = new Map<string, PS01FeasibilityEvaluation>();

/**
 * Evaluate multi-width PS01 combination feasibility (e.g. [3385, 3425, 3385] mm)
 * Strictly enforces:
 * - 3-UPS preferred
 * - 4-UPS maximum
 * - 5/6-UPS strictly forbidden (RED)
 * - Standard PS01 trim for MSL: 140–250 mm (GREEN)
 * - Relaxed PS01 trim: 120–500 mm (YELLOW)
 */
export function evaluatePS01CombinationFeasibility(
  widths: number[],
  film: string,
  thicknessMicron: number = 18
): PS01FeasibilityEvaluation {
  const cacheKey = `${film}:${thicknessMicron}:${widths.join(',')}`;
  const cached = comboFeasibilityCache.get(cacheKey);
  if (cached) return cached;

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const normalMinTrim = 140;
  const normalMaxTrim = 250;
  const ps01Ups = widths.length;

  // HARD CONSTRAINT: 5/6 UPS are strictly forbidden on PS01
  if (ps01Ups > 4 || ps01Ups < 1) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(widths.reduce((a, b) => a + b, 0) / Math.max(1, ps01Ups)),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: widths.reduce((a, b) => a + b, 0),
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `PS01 upstream jumbo manufacturing strictly forbids ${ps01Ups}-UPS (allowed: 3-UPS preferred, 4-UPS maximum)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Check any individual width against MSL max limit
  if (widths.some(w => w > 3650)) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.max(...widths),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: widths.reduce((a, b) => a + b, 0),
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `One or more jumbo widths exceed MSL maximum limit of 3650 mm`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  const totalSlitWidth = widths.reduce((a, b) => a + b, 0);
  const ps01Trim = motherDeckle - totalSlitWidth;
  const sideAUps = Math.ceil(ps01Ups / 2);
  const sideBUps = Math.floor(ps01Ups / 2);
  const isDuplexBalanced = Math.abs(sideAUps - sideBUps) <= 1;
  const efficiency = Number(((totalSlitWidth / motherDeckle) * 100).toFixed(2));
  const cutDesc = widths.join(' + ') + ` mm = ${totalSlitWidth} mm`;

  // Standard PS01 trim (140 - 250 mm) -> GREEN
  if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
    const res: PS01FeasibilityEvaluation = {
      status: 'GREEN',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: totalSlitWidth,
      ps01_trim_mm: ps01Trim,
      ps01_deckle_efficiency_percent: efficiency,
      ps01_duplex_balanced: isDuplexBalanced,
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      relaxation_type: 'NONE',
      explanation: `${ps01Ups === 3 ? 'Preferred 3-UPS' : '4-UPS'} multi-width jumbo pattern on PS01 (${cutDesc}, PS01 Trim: ${ps01Trim}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Relaxed PS01 trim (120 - 139 mm OR 251 - 500 mm) -> YELLOW
  if ((ps01Trim >= 120 && ps01Trim < normalMinTrim) || (ps01Trim > normalMaxTrim && ps01Trim <= 500)) {
    const res: PS01FeasibilityEvaluation = {
      status: 'YELLOW',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: totalSlitWidth,
      ps01_trim_mm: ps01Trim,
      ps01_deckle_efficiency_percent: efficiency,
      ps01_duplex_balanced: isDuplexBalanced,
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      relaxation_type: 'PS01_TRIM_RELAXED',
      relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for ${ps01Ups}-UPS multi-width pattern`,
      explanation: `Feasible via PS01 Trim Relaxation (${ps01Ups}-UPS): ${cutDesc}, PS01 Trim = ${ps01Trim}mm within allowed relaxation envelope (120–500 mm)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Infeasible (< 120 mm or > 500 mm) -> RED
  const redRes: PS01FeasibilityEvaluation = {
    status: 'RED',
    is_feasible: false,
    ps01_deckle_mm: motherDeckle,
    jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
    ps01_ups: ps01Ups,
    ps01_cut_combination: widths,
    ps01_total_width_mm: totalSlitWidth,
    ps01_trim_mm: ps01Trim,
    ps01_deckle_efficiency_percent: efficiency,
    ps01_duplex_balanced: isDuplexBalanced,
    side_a_ups: sideAUps,
    side_b_ups: sideBUps,
    relaxation_type: 'NONE',
    explanation: `Cannot manufacture combination on PS01: ${cutDesc}, resulting in invalid trim of ${ps01Trim} mm (strictly requires 120–500 mm envelope; trim < 120 mm or > 500 mm is RED)`,
  };
  comboFeasibilityCache.set(cacheKey, redRes);
  return redRes;
}

/**
 * Perform non-invasive PS01 Feasibility Handshake for a proposed Jumbo Width
 */
export function evaluatePS01Feasibility(
  jumboWidthMm: number,
  film: string,
  thicknessMicron: number,
  finishedWidths: number[] = [],
  baseMslTrimMm: number = 25
): PS01FeasibilityEvaluation {
  const cacheKey = `${film}:${thicknessMicron}:${jumboWidthMm}:${finishedWidths.join(',')}:${baseMslTrimMm}`;
  const cached = singleFeasibilityCache.get(cacheKey);
  if (cached) return cached;

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const normalMinTrim = 140;
  const normalMaxTrim = 250;

  // Enforce MSL hard limit on Jumbo Width
  if (jumboWidthMm > 3650) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 0,
      ps01_cut_combination: [],
      ps01_total_width_mm: 0,
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `Jumbo width ${jumboWidthMm} mm exceeds MSL maximum limit of 3650 mm`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // -------------------------------------------------------------------------
  // PRIORITY 1: 3-UPS on PS01 (First Priority for Upstream Jumbo Manufacturing)
  // PRIORITY 2: 4-UPS on PS01 (Second Priority / Maximum allowed on PS01)
  // 5-UPS and 6-UPS are STRICTLY FORBIDDEN for jumbo manufacturing on PS01
  // -------------------------------------------------------------------------

  // --- Step 1: Normal PS01 Standard Trim (140 - 250 mm) ---
  // Priority 1: 3-UPS
  const totalSlit3 = jumboWidthMm * 3;
  const ps01Trim3 = motherDeckle - totalSlit3;
  if (ps01Trim3 >= normalMinTrim && ps01Trim3 <= normalMaxTrim) {
    const res: PS01FeasibilityEvaluation = {
      status: 'GREEN',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 3,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit3,
      ps01_trim_mm: ps01Trim3,
      ps01_deckle_efficiency_percent: Number(((totalSlit3 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 1,
      relaxation_type: 'NONE',
      explanation: `Preferred 3-UPS jumbo manufacturing pattern on PS01 (3×${jumboWidthMm}mm = ${totalSlit3}mm, PS01 Trim: ${ps01Trim3}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Priority 2: 4-UPS (Only if 3-UPS is infeasible)
  const totalSlit4 = jumboWidthMm * 4;
  const ps01Trim4 = motherDeckle - totalSlit4;
  if (ps01Trim4 >= normalMinTrim && ps01Trim4 <= normalMaxTrim) {
    const res: PS01FeasibilityEvaluation = {
      status: 'GREEN',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 4,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit4,
      ps01_trim_mm: ps01Trim4,
      ps01_deckle_efficiency_percent: Number(((totalSlit4 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 2,
      relaxation_type: 'NONE',
      explanation: `Feasible 4-UPS jumbo manufacturing pattern on PS01 (4×${jumboWidthMm}mm = ${totalSlit4}mm, PS01 Trim: ${ps01Trim4}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // -------------------------------------------------------------------------
  // PRIORITY C: MSL-side Trim Adjustment (Within 20–40 mm standard window)
  // Check 3-UPS first, then 4-UPS maximum
  // -------------------------------------------------------------------------
  if (finishedWidths.length > 0) {
    const sumFinished = finishedWidths.reduce((a, b) => a + b, 0);

    // 1. Check 3-UPS with MSL trim adjustment
    for (let testMslTrim = 20; testMslTrim <= 40; testMslTrim++) {
      if (testMslTrim === baseMslTrimMm) continue;
      const adjustedJumboWidth = sumFinished + testMslTrim;
      if (adjustedJumboWidth > 3650) continue;

      const totalSlit = adjustedJumboWidth * 3;
      const ps01Trim = motherDeckle - totalSlit;
      if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
        const res: PS01FeasibilityEvaluation = {
          status: 'YELLOW',
          is_feasible: true,
          ps01_deckle_mm: motherDeckle,
          jumbo_width_mm: adjustedJumboWidth,
          ps01_ups: 3,
          ps01_cut_combination: [adjustedJumboWidth, adjustedJumboWidth, adjustedJumboWidth],
          ps01_total_width_mm: totalSlit,
          ps01_trim_mm: ps01Trim,
          ps01_deckle_efficiency_percent: Number(((totalSlit / motherDeckle) * 100).toFixed(2)),
          ps01_duplex_balanced: true,
          side_a_ups: 2,
          side_b_ups: 1,
          relaxation_type: 'MSL_TRIM_ADJUSTED',
          relaxation_flag: `NON-STANDARD MSL TRIM: Adjusted to ${testMslTrim} mm (within 20–40 mm window) to enable preferred 3-UPS on PS01`,
          explanation: `Feasible via MSL trim adjustment to ${testMslTrim}mm -> Preferred 3-UPS on PS01 (3×${adjustedJumboWidth}mm = ${totalSlit}mm, PS01 Trim: ${ps01Trim}mm)`,
        };
        singleFeasibilityCache.set(cacheKey, res);
        return res;
      }
    }

    // 2. Check 4-UPS with MSL trim adjustment (if 3-UPS impossible)
    for (let testMslTrim = 20; testMslTrim <= 40; testMslTrim++) {
      if (testMslTrim === baseMslTrimMm) continue;
      const adjustedJumboWidth = sumFinished + testMslTrim;
      if (adjustedJumboWidth > 3650) continue;

      const totalSlit = adjustedJumboWidth * 4;
      const ps01Trim = motherDeckle - totalSlit;
      if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
        const res: PS01FeasibilityEvaluation = {
          status: 'YELLOW',
          is_feasible: true,
          ps01_deckle_mm: motherDeckle,
          jumbo_width_mm: adjustedJumboWidth,
          ps01_ups: 4,
          ps01_cut_combination: [adjustedJumboWidth, adjustedJumboWidth, adjustedJumboWidth, adjustedJumboWidth],
          ps01_total_width_mm: totalSlit,
          ps01_trim_mm: ps01Trim,
          ps01_deckle_efficiency_percent: Number(((totalSlit / motherDeckle) * 100).toFixed(2)),
          ps01_duplex_balanced: true,
          side_a_ups: 2,
          side_b_ups: 2,
          relaxation_type: 'MSL_TRIM_ADJUSTED',
          relaxation_flag: `NON-STANDARD MSL TRIM: Adjusted to ${testMslTrim} mm (within 20–40 mm window) to enable 4-UPS on PS01`,
          explanation: `Feasible via MSL trim adjustment to ${testMslTrim}mm -> 4-UPS on PS01 (4×${adjustedJumboWidth}mm = ${totalSlit}mm, PS01 Trim: ${ps01Trim}mm)`,
        };
        singleFeasibilityCache.set(cacheKey, res);
        return res;
      }
    }
  }

  // -------------------------------------------------------------------------
  // PRIORITY D & E: Upstream PS01-side Trim Relaxation (Expanded 120 - 500 mm window)
  // Check 3-UPS first, then 4-UPS maximum (5/6-UPS strictly forbidden)
  // -------------------------------------------------------------------------
  // 1. Check 3-UPS under relaxed PS01 trim
  if (ps01Trim3 >= 120 && ps01Trim3 <= 500) {
    const res: PS01FeasibilityEvaluation = {
      status: 'YELLOW',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 3,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit3,
      ps01_trim_mm: ps01Trim3,
      ps01_deckle_efficiency_percent: Number(((totalSlit3 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 1,
      relaxation_type: 'PS01_TRIM_RELAXED',
      relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim3} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for 3-UPS`,
      explanation: `Feasible via Upstream PS01 Trim Relaxation (3-UPS): 3×${jumboWidthMm}mm = ${totalSlit3}mm, PS01 Trim = ${ps01Trim3}mm`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // 2. Check 4-UPS under relaxed PS01 trim
  if (ps01Trim4 >= 120 && ps01Trim4 <= 500) {
    const res: PS01FeasibilityEvaluation = {
      status: 'YELLOW',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 4,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit4,
      ps01_trim_mm: ps01Trim4,
      ps01_deckle_efficiency_percent: Number(((totalSlit4 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 2,
      relaxation_type: 'PS01_TRIM_RELAXED',
      relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim4} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for 4-UPS`,
      explanation: `Feasible via Upstream PS01 Trim Relaxation (4-UPS): 4×${jumboWidthMm}mm = ${totalSlit4}mm, PS01 Trim = ${ps01Trim4}mm`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Otherwise completely infeasible (5/6-UPS forbidden on PS01)
  const finalRedRes: PS01FeasibilityEvaluation = {
    status: 'RED',
    is_feasible: false,
    ps01_deckle_mm: motherDeckle,
    jumbo_width_mm: jumboWidthMm,
    ps01_ups: 0,
    ps01_cut_combination: [],
    ps01_total_width_mm: 0,
    ps01_trim_mm: 0,
    ps01_deckle_efficiency_percent: 0,
    ps01_duplex_balanced: false,
    side_a_ups: 0,
    side_b_ups: 0,
    relaxation_type: 'NONE',
    explanation: `Cannot manufacture jumbo width ${jumboWidthMm} mm on PS01: 3-UPS and 4-UPS are infeasible, and 5/6-UPS are strictly forbidden for upstream jumbo roll manufacturing (10,400 mm master deckle)`,
  };
  singleFeasibilityCache.set(cacheKey, finalRedRes);
  return finalRedRes;
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan or multi-width jumbo combination.
 * STRICT REQUIREMENT: Each Jumbo Plan has its own isolated Factory Sheet with NO cross-plan data mixing.
 */
export function generatePS01PlanForJumboCombination(
  jumboWidths: number[],
  planIndex: number,
  film: string,
  lengthM: number,
  thickness: number = 18,
  associatedReqs: JumboRequirement[] = [],
  createdBy: string = 'M.USMAN (Planner)',
  repetitions: number = 1
): SlitterPlan {
  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const ps01Ups = jumboWidths.length;
  const sideAUps = Math.ceil(ps01Ups / 2);
  const sideBUps = Math.floor(ps01Ups / 2);
  const totalSlitWidth = jumboWidths.reduce((a, b) => a + b, 0);
  const trimMm = motherDeckle - totalSlitWidth;
  const density = 0.91;
  const dateStr = new Date().toISOString();
  const displayDate = new Date().toLocaleDateString('en-GB');

  // Authoritative weight calculation per item
  const items: PlanItem[] = [];
  let currentSideAArm = 1;
  let currentSideBArm = 9;
  let totalPlannedQuantityKg = 0;

  const planId = `ps01-plan-${Date.now()}-${planIndex + 1}`;
  const widthSummary = jumboWidths.length <= 2 
    ? jumboWidths.join('+') + 'MM' 
    : `${jumboWidths[0]}+${jumboWidths[1]}+${jumboWidths[2]}${jumboWidths[3] ? '+' + jumboWidths[3] : ''}MM`;
  const planNumber = `PS01-JP${planIndex + 1}-${film}-${widthSummary}`;
  const segmentId = `seg-ps01-${planIndex + 1}-1`;

  const uniqueWidths = Array.from(new Set(jumboWidths));

  for (let i = 0; i < ps01Ups; i++) {
    const width = jumboWidths[i];
    const isSideA = i % 2 === 0 ? (currentSideAArm <= sideAUps) : (currentSideBArm > 8 + sideBUps);
    const station: 'SIDE_A' | 'SIDE_B' = isSideA ? 'SIDE_A' : 'SIDE_B';
    const physicalArm = station === 'SIDE_A' ? currentSideAArm++ : currentSideBArm++;
    const posIndex = i + 1;

    const singleReelWeightKg = Number(((width * lengthM * thickness * density) / 1000000).toFixed(2));
    const itemTotalWeightKg = Number((singleReelWeightKg * repetitions).toFixed(2));
    totalPlannedQuantityKg += itemTotalWeightKg;

    const matchedReq = associatedReqs.find(r => r.required_jumbo_width_mm === width) || associatedReqs[0];
    const formatWidthsMultiplier = (widths: number[]): string => {
      if (!widths || widths.length === 0) return '';
      const counts = new Map<number, number>();
      for (const w of widths) {
        counts.set(w, (counts.get(w) || 0) + 1);
      }
      return Array.from(counts.entries())
        .map(([w, count]) => (count > 1 ? `${w}*${count}` : `${w}`))
        .join(' + ');
    };
    const customerLabel = matchedReq 
      ? `MSL ${matchedReq.ups}-UPS: ${formatWidthsMultiplier(matchedReq.finished_widths_covered || [])}`
      : `${width}mm JUMBO`;

    const uniqueIndex = uniqueWidths.indexOf(width);
    const sizeItemNumber = (uniqueIndex + 1) * 10;

    items.push({
      id: `item-${planId}-${posIndex}`,
      plan_id: planId,
      segment_id: segmentId,
      position: physicalArm,
      positions: [physicalArm],
      position_label: `Pos ${posIndex} (Arm ${physicalArm})`,
      station: station,
      sales_order: `JR-${film}-${width}`,
      item_number: sizeItemNumber,
      customer: customerLabel,
      film: film,
      width_mm: width,
      length_m: lengthM,
      core: 6,
      treatment_side: 'OS',
      reels: repetitions,
      ups: 1,
      initial_ups: 1,
      deckle_mm: width,
      weight_per_pack_kg: singleReelWeightKg,
      total_weight_kg: itemTotalWeightKg,
      is_closed: true,
    });
  }

  totalPlannedQuantityKg = Number(totalPlannedQuantityKg.toFixed(2));
  const singleMillRollWeightKg = Number(((motherDeckle * lengthM * thickness * density) / 1000000).toFixed(2));
  const singleTrimWeightKg = Number(((trimMm * lengthM * thickness * density) / 1000000).toFixed(2));
  const millRollWeightKg = Number((singleMillRollWeightKg * repetitions).toFixed(2));
  const trimWeightKg = Number((singleTrimWeightKg * repetitions).toFixed(2));
  const wastePercent = Number(((trimMm / motherDeckle) * 100).toFixed(2));

  const segment: PlanSegment = {
    id: segmentId,
    plan_id: planId,
    segment_number: 1,
    name: `Jumbo Slit Layout (${ps01Ups}-UPS on 10,400mm Mother Deckle)`,
    start_pack: 1,
    end_pack: repetitions,
    repetitions: repetitions,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    ups: ps01Ups,
    items: items,
  };

  const isRelaxed = trimMm < 140 || trimMm > 250;

  return {
    id: planId,
    planning_run_id: `run-jumbo-${film}`,
    plan_number: planNumber,
    machine_id: 'PS01',
    machine_name: 'PRIMARY SLITTER 1 (PS01)',
    film: film,
    thickness_micron: thickness,
    density: density,
    deckle_mm: motherDeckle,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    allowed_trim_mm: 250,
    remaining_web_mm: 0,
    ups: ps01Ups,
    max_ups_capacity: 16,
    repetitions: repetitions,
    length_m: lengthM,
    planned_mr_length_m: lengthM,
    mill_roll_weight_kg: millRollWeightKg,
    trim_weight_kg: trimWeightKg,
    waste_percent: wastePercent,
    planned_quantity_kg: totalPlannedQuantityKg,
    order_weight_kg: totalPlannedQuantityKg,
    total_reels: ps01Ups * repetitions,
    weight_per_pack_total_kg: Number((totalPlannedQuantityKg / repetitions).toFixed(2)),
    rejection_material: `R-${film}`,
    trim_rule_mode: isRelaxed ? 'RELAXED_50MM' : 'NORMAL',
    min_trim_mm_used: isRelaxed ? 120 : 140,
    max_trim_mm_used: isRelaxed ? 500 : 250,
    duplex_layout: {
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      is_dual_core: false,
      is_dual_length: false,
      balance_delta: Math.abs(sideAUps - sideBUps),
    },
    doc_ref: 'APS/QR/PL/01',
    rev_no: 0,
    issue_date: displayDate,
    items: items,
    changes: [],
    segments: [segment],
    status: 'APPROVED',
    approved_by: createdBy,
    approved_at: dateStr,
    created_at: dateStr,
  };
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for a complete Mother Roll Deckle Run Group.
 * This accurately calculates:
 * 1. The exact Number of Mother Roll Packs (Sets / Repetitions) required to satisfy all physical rolls.
 * 2. The proper length (m) of the Jumbo Mother Rolls.
 * 3. Accurate Knife cut allocations to each downstream Metallizer (MSL) Plan.
 */
export function generatePS01PlanForDeckleGroup(
  reqs: JumboRequirement[],
  runIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  if (!reqs || reqs.length === 0) {
    throw new Error('No requirements provided for mother run group');
  }

  const primaryReq = reqs[0];
  const feasibility = primaryReq.ps01_feasibility;
  const cutCombination = feasibility?.ps01_cut_combination && feasibility.ps01_cut_combination.length > 0
    ? [...feasibility.ps01_cut_combination]
    : Array(feasibility?.ps01_ups || (primaryReq.required_jumbo_width_mm <= 2600 ? 4 : 3)).fill(primaryReq.required_jumbo_width_mm);

  // Count how many times each jumbo width appears in this mother deckle pattern
  const patternWidthCounts = new Map<number, number>();
  cutCombination.forEach(w => patternWidthCounts.set(w, (patternWidthCounts.get(w) || 0) + 1));

  // Map each cut position to the specific MSL requirement that utilizes this jumbo width
  const associatedReqs: JumboRequirement[] = [];
  const assignedCountsPerReq = new Map<string, number>();

  for (let i = 0; i < cutCombination.length; i++) {
    const cutWidth = cutCombination[i];
    // Find matching req with exact width or closest width
    const matchingReqs = reqs.filter(r => r.required_jumbo_width_mm === cutWidth);
    let assignedReq = matchingReqs[0] || primaryReq;

    if (matchingReqs.length > 1) {
      // Pick the one that has been assigned fewer times so far
      matchingReqs.sort((a, b) => (assignedCountsPerReq.get(a.id) || 0) - (assignedCountsPerReq.get(b.id) || 0));
      assignedReq = matchingReqs[0];
    }

    associatedReqs.push(assignedReq);
    assignedCountsPerReq.set(assignedReq.id, (assignedCountsPerReq.get(assignedReq.id) || 0) + 1);
  }

  // Calculate repetitions (number of PS01 Mother Roll packs/sets needed)
  // Each mother roll set produces `assignedCountsPerReq` rolls of that jumbo width.
  // For each req, sets needed = Math.ceil(required_rolls_count / count_in_pattern)
  let setsNeeded = 1;
  for (const r of reqs) {
    const usageInPattern = patternWidthCounts.get(r.required_jumbo_width_mm) || 1;
    const rollsCount = r.required_rolls_count || 1;
    const neededForReq = Math.ceil(rollsCount / usageInPattern);
    if (neededForReq > setsNeeded) {
      setsNeeded = neededForReq;
    }
  }

  const lengthM = Math.max(...reqs.map(r => r.required_jumbo_length_m || 20000));
  const thickness = primaryReq.thickness_micron || 18;

  return generatePS01PlanForJumboCombination(
    cutCombination,
    runIndex - 1,
    film,
    lengthM,
    thickness,
    associatedReqs,
    createdBy,
    setsNeeded
  );
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan.
 * STRICT REQUIREMENT: Each Jumbo Plan has its own isolated Factory Sheet with NO cross-plan data mixing.
 */
export function generatePS01PlanForSingleJumbo(
  req: JumboRequirement,
  planIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  const feasibilityCuts = req.ps01_feasibility?.ps01_cut_combination;
  const widths = feasibilityCuts && feasibilityCuts.length > 0
    ? [...feasibilityCuts]
    : Array(req.ps01_feasibility?.ps01_ups || (req.required_jumbo_width_mm <= 2600 ? 4 : 3)).fill(req.required_jumbo_width_mm);

  const upsInPattern = widths.filter(w => w === req.required_jumbo_width_mm).length || 1;
  const setsNeeded = Math.max(1, Math.ceil((req.required_rolls_count || 1) / upsInPattern));

  return generatePS01PlanForJumboCombination(
    widths,
    planIndex,
    film,
    req.required_jumbo_length_m,
    req.thickness_micron || 18,
    Array(widths.length).fill(req),
    createdBy,
    setsNeeded
  );
}

/**
 * Generate a customer-standard SlitterPlan for a Metallizer Slitter (MSL) Plan.
 * This formats the MSL slitting job in the standard BOPP factory sheet layout (PlanDetailViewer),
 * with duplex arms, knife positions, customer sales orders, roll repetitions (packs),
 * jumbo mount width, trim waste, and quality checks.
 */
export function generateMSLSlitterPlan(
  req: JumboRequirement,
  planIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  const mountJumboWidth = req.required_jumbo_width_mm;
  const finishedCuts = req.finished_widths_covered || [];
  const mslUps = finishedCuts.length || req.ups || 1;
  const sideAUps = Math.ceil(mslUps / 2);
  const sideBUps = Math.floor(mslUps / 2);
  const totalSlitWidth = finishedCuts.reduce((a, b) => a + b, 0);
  const trimMm = req.expected_trim_mm !== undefined ? req.expected_trim_mm : Math.max(0, mountJumboWidth - totalSlitWidth);
  const density = 0.91;
  const jumboLengthM = req.required_jumbo_length_m || 20000;
  const thickness = req.thickness_micron || 18;
  const jumboRollsCount = req.required_rolls_count || 1;
  const dateStr = new Date().toISOString();
  const displayDate = new Date().toLocaleDateString('en-GB');

  // Derive exact Reel / Pack Length from covered orders (e.g. 18,700m or 20,000m or 9,350m)
  const ordersCovered = req.orders_covered || [];
  const coveredLengths = ordersCovered.map(o => o.length_m).filter(Boolean);
  const packLengthM = coveredLengths.length > 0 
    ? Math.max(...coveredLengths) 
    : Math.round(jumboLengthM / Math.max(1, req.package_multiple || 1));
  const setsPerJumbo = Math.max(1, Math.round(jumboLengthM / packLengthM));
  const totalPacks = jumboRollsCount * setsPerJumbo;

  const planId = `msl-slitter-plan-${req.id || planIndex + 1}`;
  const widthSummary = finishedCuts.length <= 3 
    ? finishedCuts.join('+') + 'MM' 
    : `${finishedCuts.slice(0, 3).join('+')}+${finishedCuts.length - 3}MORE`;
  const planNumber = `MSL-P${planIndex + 1}-${film}-${mountJumboWidth}MM-(${widthSummary})`;
  const segmentId = `seg-msl-${planIndex + 1}-1`;

  // 1. First, map all cuts to their matching customer orders to determine widths & lengths
  interface RawCutItem {
    posIndex: number;
    cutWidth: number;
    matchedOrder: any;
    customerRequiredLengthM: number;
    salesOrder: string;
    itemNumber: number;
    customer: string;
  }

  const allocatedWidthCount = new Map<number, number>();
  const rawCuts: RawCutItem[] = [];

  for (let i = 0; i < mslUps; i++) {
    const cutWidth = finishedCuts[i] || 0;
    const posIndex = i + 1;

    // Find the order for this cut width
    const matchingOrders = ordersCovered.filter(o => o.width_mm === cutWidth);
    const seenIndex = allocatedWidthCount.get(cutWidth) || 0;
    allocatedWidthCount.set(cutWidth, seenIndex + 1);
    const matchedOrder = matchingOrders[seenIndex % matchingOrders.length] || matchingOrders[0] || ordersCovered[0];
    const customerRequiredLengthM = matchedOrder?.length_m || packLengthM;

    const salesOrder = matchedOrder?.sales_order ? `SO#${matchedOrder.sales_order}` : `SO-MSL-${posIndex}`;
    const itemNumber = matchedOrder?.item_number || posIndex * 10;
    const customer = matchedOrder?.customer || 'METALLIZED FILM CUSTOMER';

    rawCuts.push({
      posIndex,
      cutWidth,
      matchedOrder,
      customerRequiredLengthM,
      salesOrder,
      itemNumber,
      customer,
    });
  }

  // 2. Determine unique lengths
  const uniqueLengths = Array.from(new Set(rawCuts.map(c => c.customerRequiredLengthM))).sort((a, b) => b - a); // Descending: [22200, 11100]

  // 3. Assign Station (SIDE A vs SIDE B) and physical duplex arms (1..8 on A, 9..16 on B)
  // CRITICAL DUPLEX RULE: A rewind shaft CANNOT mix different roll lengths!
  // All rolls on Side A shaft MUST wind length L_A. All rolls on Side B shaft MUST wind length L_B.
  const items: PlanItem[] = [];
  let currentSideAArm = 1;
  let currentSideBArm = 9;
  let totalPlannedQuantityKg = 0;

  if (uniqueLengths.length > 1) {
    // Dual Length: Put longer length on Side A, shorter length on Side B
    const longLen = uniqueLengths[0];
    const shortLen = uniqueLengths[1];

    const sideACuts = rawCuts.filter(c => c.customerRequiredLengthM === longLen);
    const sideBCuts = rawCuts.filter(c => c.customerRequiredLengthM === shortLen);

    // Side A items
    sideACuts.forEach(c => {
      const physicalArm = currentSideAArm++;
      const reelsPerPack = Math.max(1, Math.round(packLengthM / c.customerRequiredLengthM));
      const totalReelsForCut = totalPacks * reelsPerPack;
      const singleReelWeightKg = Number(((c.cutWidth * c.customerRequiredLengthM * thickness * density) / 1000000).toFixed(2));
      const itemTotalWeightKg = Number((singleReelWeightKg * totalReelsForCut).toFixed(2));
      totalPlannedQuantityKg += itemTotalWeightKg;

      items.push({
        id: `item-${planId}-${c.posIndex}`,
        plan_id: planId,
        segment_id: segmentId,
        position: physicalArm,
        positions: [physicalArm],
        position_label: `Pos ${c.posIndex} (Arm ${physicalArm})`,
        station: 'SIDE_A',
        sales_order: c.salesOrder,
        item_number: c.itemNumber,
        customer: c.customer,
        film: film,
        width_mm: c.cutWidth,
        length_m: c.customerRequiredLengthM,
        core: 6,
        treatment_side: 'OS',
        reels: totalReelsForCut,
        ups: 1,
        initial_ups: 1,
        deckle_mm: c.cutWidth,
        weight_per_pack_kg: Number((singleReelWeightKg * reelsPerPack).toFixed(2)),
        total_weight_kg: itemTotalWeightKg,
        is_closed: true,
      });
    });

    // Side B items
    sideBCuts.forEach(c => {
      const physicalArm = currentSideBArm++;
      const reelsPerPack = Math.max(1, Math.round(packLengthM / c.customerRequiredLengthM));
      const totalReelsForCut = totalPacks * reelsPerPack;
      const singleReelWeightKg = Number(((c.cutWidth * c.customerRequiredLengthM * thickness * density) / 1000000).toFixed(2));
      const itemTotalWeightKg = Number((singleReelWeightKg * totalReelsForCut).toFixed(2));
      totalPlannedQuantityKg += itemTotalWeightKg;

      items.push({
        id: `item-${planId}-${c.posIndex}`,
        plan_id: planId,
        segment_id: segmentId,
        position: physicalArm,
        positions: [physicalArm],
        position_label: `Pos ${c.posIndex} (Arm ${physicalArm})`,
        station: 'SIDE_B',
        sales_order: c.salesOrder,
        item_number: c.itemNumber,
        customer: c.customer,
        film: film,
        width_mm: c.cutWidth,
        length_m: c.customerRequiredLengthM,
        core: 6,
        treatment_side: 'OS',
        reels: totalReelsForCut,
        ups: 1,
        initial_ups: 1,
        deckle_mm: c.cutWidth,
        weight_per_pack_kg: Number((singleReelWeightKg * reelsPerPack).toFixed(2)),
        total_weight_kg: itemTotalWeightKg,
        is_closed: true,
      });
    });

    // Sort items by posIndex for clean visual layout
    items.sort((a, b) => {
      const numA = parseInt(a.position_label.match(/\d+/)?.[0] || '0', 10);
      const numB = parseInt(b.position_label.match(/\d+/)?.[0] || '0', 10);
      return numA - numB;
    });
  } else {
    // Single Length: Alternate between Side A and Side B
    rawCuts.forEach((c, idx) => {
      const isSideA = idx % 2 === 0;
      const station: 'SIDE_A' | 'SIDE_B' = isSideA ? 'SIDE_A' : 'SIDE_B';
      const physicalArm = station === 'SIDE_A' ? currentSideAArm++ : currentSideBArm++;

      const reelsPerPack = Math.max(1, Math.round(packLengthM / c.customerRequiredLengthM));
      const totalReelsForCut = totalPacks * reelsPerPack;
      const singleReelWeightKg = Number(((c.cutWidth * c.customerRequiredLengthM * thickness * density) / 1000000).toFixed(2));
      const itemTotalWeightKg = Number((singleReelWeightKg * totalReelsForCut).toFixed(2));
      totalPlannedQuantityKg += itemTotalWeightKg;

      items.push({
        id: `item-${planId}-${c.posIndex}`,
        plan_id: planId,
        segment_id: segmentId,
        position: physicalArm,
        positions: [physicalArm],
        position_label: `Pos ${c.posIndex} (Arm ${physicalArm})`,
        station: station,
        sales_order: c.salesOrder,
        item_number: c.itemNumber,
        customer: c.customer,
        film: film,
        width_mm: c.cutWidth,
        length_m: c.customerRequiredLengthM,
        core: 6,
        treatment_side: 'OS',
        reels: totalReelsForCut,
        ups: 1,
        initial_ups: 1,
        deckle_mm: c.cutWidth,
        weight_per_pack_kg: Number((singleReelWeightKg * reelsPerPack).toFixed(2)),
        total_weight_kg: itemTotalWeightKg,
        is_closed: true,
      });
    });
  }

  totalPlannedQuantityKg = Number(totalPlannedQuantityKg.toFixed(2));
  const singlePackMillRollWeightKg = Number(((mountJumboWidth * packLengthM * thickness * density) / 1000000).toFixed(2));
  const singlePackTrimWeightKg = Number(((trimMm * packLengthM * thickness * density) / 1000000).toFixed(2));
  const millRollWeightKg = Number((singlePackMillRollWeightKg * totalPacks).toFixed(2));
  const trimWeightKg = Number((singlePackTrimWeightKg * totalPacks).toFixed(2));
  const wastePercent = Number(((trimMm / mountJumboWidth) * 100).toFixed(2));
  const totalReelsCount = items.reduce((sum, item) => sum + item.reels, 0);

  const segment: PlanSegment = {
    id: segmentId,
    plan_id: planId,
    segment_number: 1,
    name: `MSL Finished Slit Pattern (${mslUps}-UPS on ${mountJumboWidth}mm Jumbo Mount)`,
    start_pack: 1,
    end_pack: totalPacks,
    repetitions: totalPacks,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    ups: mslUps,
    items: items,
  };

  const sideAItems = items.filter(it => it.station === 'SIDE_A');
  const sideBItems = items.filter(it => it.station === 'SIDE_B');
  const actualSideAUps = sideAItems.length;
  const actualSideBUps = sideBItems.length;
  const sideALen = sideAItems[0]?.length_m || packLengthM;
  const sideBLen = sideBItems[0]?.length_m || packLengthM;
  const isDualLen = sideAItems.some(it => it.length_m !== sideALen) || sideBItems.some(it => it.length_m !== sideBLen) || (sideALen !== sideBLen);

  return {
    id: planId,
    planning_run_id: `run-msl-${film}`,
    plan_number: planNumber,
    machine_id: 'MSL',
    machine_name: 'METALLIZER SLITTER (MSL)',
    film: film,
    thickness_micron: thickness,
    density: density,
    deckle_mm: mountJumboWidth,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    allowed_trim_mm: 50,
    remaining_web_mm: 0,
    ups: mslUps,
    max_ups_capacity: 16,
    repetitions: totalPacks,
    length_m: packLengthM,
    planned_mr_length_m: packLengthM,
    mill_roll_weight_kg: millRollWeightKg,
    trim_weight_kg: trimWeightKg,
    waste_percent: wastePercent,
    planned_quantity_kg: totalPlannedQuantityKg,
    order_weight_kg: totalPlannedQuantityKg,
    total_reels: totalReelsCount,
    weight_per_pack_total_kg: Number((totalPlannedQuantityKg / totalPacks).toFixed(2)),
    rejection_material: `R-${film}`,
    trim_rule_mode: 'NORMAL',
    min_trim_mm_used: 10,
    max_trim_mm_used: 50,
    duplex_layout: {
      side_a_ups: actualSideAUps,
      side_b_ups: actualSideBUps,
      is_dual_core: false,
      is_dual_length: isDualLen,
      side_a_length_m: sideALen,
      side_b_length_m: sideBLen,
      balance_delta: Math.abs(actualSideAUps - actualSideBUps),
    },
    doc_ref: 'APS/QR/MSL/01',
    rev_no: 0,
    issue_date: displayDate,
    items: items,
    changes: [],
    segments: [segment],
    status: 'APPROVED',
    approved_by: createdBy,
    approved_at: dateStr,
    created_at: dateStr,
    notes: `Mount Jumbo: ${mountJumboWidth} mm | Pack Length: ${packLengthM.toLocaleString()} m | Total Packs: ${totalPacks} Packs (${jumboRollsCount} Jumbo Roll${jumboRollsCount > 1 ? 's' : ''} × ${setsPerJumbo} Sets) | Upstream PS01 Origin: ${req.ps01_parent_deckle_id || 'PS01 Mother Run'}`,
  };
}

/**
 * Generate optimal PS01 Manufacturing Slitter Plans for approved Jumbo Requirements.
 * CRITICAL OPTIMIZATION RULES:
 * 1. Minimizes unnecessary jumbo-roll manufacturing and maximizes usable jumbo length.
 * 2. Allows different jumbo widths in the same 3-UPS or 4-UPS PS01 pattern (e.g. 3385 + 3425 + 3385 mm).
 * 3. 3-UPS is preferred; 4-UPS is maximum; 5/6-UPS are strictly forbidden.
 * 4. Intelligently consolidates similar jumbo widths (within 15mm) to reduce PS01 knife setups.
 * 5. Guarantees every individual jumbo-roll manufacturing plan maintains its own separate Factory Sheet.
 */
export function generatePS01ManufacturingPlansForJumbos(
  requirements: JumboRequirement[],
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): {
  plans: SlitterPlan[];
  film: string;
  logs: any[];
} {
  if (requirements.length === 0) {
    return { plans: [], film, logs: [] };
  }

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const thickness = requirements[0]?.thickness_micron || 18;

  // Represent roll requirements as distinct demand buckets with remaining roll counts
  interface JumboDemandBucket {
    id: string;
    req: JumboRequirement;
    width: number;
    length: number;
    remainingRolls: number;
  }

  const buckets: JumboDemandBucket[] = requirements.map((req, idx) => ({
    id: req.id || `req-${idx}`,
    req,
    width: req.required_jumbo_width_mm,
    length: req.required_jumbo_length_m,
    remainingRolls: req.required_rolls_count || 1,
  }));

  const logs: any[] = [];

  // Intelligent consolidation of similar jumbo widths (within 15 mm)
  for (let i = 0; i < buckets.length; i++) {
    for (let j = i + 1; j < buckets.length; j++) {
      const diff = Math.abs(buckets[i].width - buckets[j].width);
      if (diff > 0 && diff <= 15) {
        const commonWidth = Math.round((buckets[i].width + buckets[j].width) / 2);
        const trim = motherDeckle - (commonWidth * 3);
        if (trim >= 120 && trim <= 500) {
          const originalI = buckets[i].width;
          const originalJ = buckets[j].width;
          buckets[i].width = commonWidth;
          buckets[j].width = commonWidth;
          logs.push({
            step: logs.length + 1,
            message: `Consolidated similar jumbo widths (${originalI}mm & ${originalJ}mm) to common width ${commonWidth}mm to reduce PS01 setup changes.`,
            type: 'INFO',
          });
        }
      }
    }
  }

  const plans: SlitterPlan[] = [];
  let planIndex = 0;

  // Fast combinatorial search on distinct buckets
  let activeBuckets = buckets.filter(b => b.remainingRolls > 0);

  while (activeBuckets.length > 0) {
    let bestCombo: {
      b1: JumboDemandBucket;
      b2: JumboDemandBucket;
      b3: JumboDemandBucket;
      b4?: JumboDemandBucket;
      widths: number[];
      ups: number;
      trim: number;
      status: 'GREEN' | 'YELLOW';
      score: number;
      i: number;
      j: number;
      k: number;
      l?: number;
    } | null = null;

    // 1. Check 3-UPS across distinct buckets (Priority 1)
    const bLen = activeBuckets.length;
    for (let i = 0; i < bLen; i++) {
      const b1 = activeBuckets[i];
      for (let j = i; j < bLen; j++) {
        const b2 = activeBuckets[j];
        for (let k = j; k < bLen; k++) {
          const b3 = activeBuckets[k];

          // Check if sufficient rolls exist for this combination
          let canForm = false;
          if (i === j && j === k) {
            canForm = b1.remainingRolls >= 3;
          } else if (i === j) {
            canForm = b1.remainingRolls >= 2 && b3.remainingRolls >= 1;
          } else if (j === k) {
            canForm = b1.remainingRolls >= 1 && b2.remainingRolls >= 2;
          } else {
            canForm = b1.remainingRolls >= 1 && b2.remainingRolls >= 1 && b3.remainingRolls >= 1;
          }

          if (!canForm) continue;

          const widths = [b1.width, b2.width, b3.width];
          const evalResult = evaluatePS01CombinationFeasibility(widths, film, thickness);

          if (evalResult.is_feasible && evalResult.status !== 'RED') {
            let score = 20000;
            if (evalResult.status === 'GREEN') score += 5000;
            score -= Math.abs(evalResult.ps01_trim_mm - 190);
            if (b1.width === b2.width && b2.width === b3.width) score += 2000;
            else if (b1.width === b2.width || b2.width === b3.width || b1.width === b3.width) score += 1000;

            if (!bestCombo || score > bestCombo.score) {
              bestCombo = {
                b1,
                b2,
                b3,
                widths,
                ups: 3,
                trim: evalResult.ps01_trim_mm,
                status: evalResult.status,
                score,
                i,
                j,
                k,
              };
            }
          }
        }
      }
    }

    // 2. If no 3-UPS found, try 4-UPS across distinct buckets (Priority 2)
    if (!bestCombo) {
      for (let i = 0; i < bLen; i++) {
        const b1 = activeBuckets[i];
        for (let j = i; j < bLen; j++) {
          const b2 = activeBuckets[j];
          for (let k = j; k < bLen; k++) {
            const b3 = activeBuckets[k];
            for (let l = k; l < bLen; l++) {
              const b4 = activeBuckets[l];

              // Count usage per bucket index
              const counts: Record<number, number> = {};
              counts[i] = (counts[i] || 0) + 1;
              counts[j] = (counts[j] || 0) + 1;
              counts[k] = (counts[k] || 0) + 1;
              counts[l] = (counts[l] || 0) + 1;

              const canForm = Object.entries(counts).every(([idx, needed]) => activeBuckets[Number(idx)].remainingRolls >= needed);
              if (!canForm) continue;

              const widths = [b1.width, b2.width, b3.width, b4.width];
              const evalResult = evaluatePS01CombinationFeasibility(widths, film, thickness);

              if (evalResult.is_feasible && evalResult.status !== 'RED') {
                let score = 10000;
                if (evalResult.status === 'GREEN') score += 3000;
                score -= Math.abs(evalResult.ps01_trim_mm - 190);

                if (!bestCombo || score > bestCombo.score) {
                  bestCombo = {
                    b1,
                    b2,
                    b3,
                    b4,
                    widths,
                    ups: 4,
                    trim: evalResult.ps01_trim_mm,
                    status: evalResult.status,
                    score,
                    i,
                    j,
                    k,
                    l,
                  };
                }
              }
            }
          }
        }
      }
    }

    // 3. Batch apply the best combo
    if (bestCombo) {
      const { b1, b2, b3, b4, widths, ups, i, j, k, l } = bestCombo;
      let batchCycles = Infinity;

      if (ups === 3) {
        if (i === j && j === k) {
          batchCycles = Math.floor(b1.remainingRolls / 3);
        } else if (i === j) {
          batchCycles = Math.min(Math.floor(b1.remainingRolls / 2), b3.remainingRolls);
        } else if (j === k) {
          batchCycles = Math.min(b1.remainingRolls, Math.floor(b2.remainingRolls / 2));
        } else {
          batchCycles = Math.min(b1.remainingRolls, b2.remainingRolls, b3.remainingRolls);
        }
      } else if (ups === 4 && b4 !== undefined && l !== undefined) {
        const counts: Record<number, number> = {};
        counts[i] = (counts[i] || 0) + 1;
        counts[j] = (counts[j] || 0) + 1;
        counts[k] = (counts[k] || 0) + 1;
        counts[l] = (counts[l] || 0) + 1;
        for (const [idx, needed] of Object.entries(counts)) {
          const avail = Math.floor(activeBuckets[Number(idx)].remainingRolls / needed);
          if (avail < batchCycles) batchCycles = avail;
        }
      }

      batchCycles = Math.max(1, batchCycles);
      const reqs = ups === 3 ? [b1.req, b2.req, b3.req] : [b1.req, b2.req, b3.req, b4!.req];
      const maxLen = Math.max(...(ups === 3 ? [b1.length, b2.length, b3.length] : [b1.length, b2.length, b3.length, b4!.length]));

      for (let c = 0; c < batchCycles; c++) {
        const plan = generatePS01PlanForJumboCombination(
          widths,
          planIndex++,
          film,
          maxLen,
          thickness,
          reqs,
          createdBy
        );
        plans.push(plan);
      }

      // Deduct used roll quantities
      if (ups === 3) {
        if (i === j && j === k) {
          b1.remainingRolls -= 3 * batchCycles;
        } else if (i === j) {
          b1.remainingRolls -= 2 * batchCycles;
          b3.remainingRolls -= batchCycles;
        } else if (j === k) {
          b1.remainingRolls -= batchCycles;
          b2.remainingRolls -= 2 * batchCycles;
        } else {
          b1.remainingRolls -= batchCycles;
          b2.remainingRolls -= batchCycles;
          b3.remainingRolls -= batchCycles;
        }
      } else if (ups === 4 && l !== undefined) {
        const counts: Record<number, number> = {};
        counts[i] = (counts[i] || 0) + 1;
        counts[j] = (counts[j] || 0) + 1;
        counts[k] = (counts[k] || 0) + 1;
        counts[l] = (counts[l] || 0) + 1;
        for (const [idx, needed] of Object.entries(counts)) {
          activeBuckets[Number(idx)].remainingRolls -= needed * batchCycles;
        }
      }

      activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
    } else {
      // 4. For remaining single rolls, generate isolated single-requirement plans
      const singleBucket = activeBuckets[0];
      while (singleBucket.remainingRolls > 0) {
        const singlePlan = generatePS01PlanForSingleJumbo(singleBucket.req, planIndex++, film, createdBy);
        plans.push(singlePlan);
        singleBucket.remainingRolls--;
      }
      activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
    }
  }

  logs.push({
    step: logs.length + 1,
    message: `Generated ${plans.length} optimized PS01 Manufacturing Plan(s) for ${film} jumbo rolls with isolated Factory Sheets. Minimized setups and waste.`,
    type: 'SUCCESS' as const,
    data: { planCount: plans.length },
  });

  return {
    plans,
    film,
    logs,
  };
}

/**
 * Backward compatibility alias
 */
export function generatePS01ManufacturingPlanForJumbos(
  requirements: JumboRequirement[],
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): {
  plans: SlitterPlan[];
  film: string;
  logs: any[];
} {
  return generatePS01ManufacturingPlansForJumbos(requirements, film, createdBy);
}

